#pragma once
#include <string>
#include <array>

inline const std::string DEFAULT_PATH       = "${output_dir}/${section_name}";
inline const std::string DEFAULT_FORMAT     = "${color_name} #${color_value}";
inline const std::string DEFAULT_FORMAT_ID  = "${color_name} #${color_value}";
inline const std::string DEFAULT_COMMENT    = "#";
inline const std::string DEFAULT_MODE       = "modify-add";

inline const std::array<std::string, 2> CONFIG_VARIABLES {
    "section_name",
    "output_dir"
};

inline const std::array<std::string, 3> COLOR_VARIABLES {

    "color_name",
    "color_id",
    "color_value"

};

inline const std::string DEFAULT_CONFIG{

    "# Autogenerated default config\n"
    "\n"
    "[default]\n"
    "path = " + DEFAULT_PATH + "\n"
    "format = " + DEFAULT_FORMAT + "\n"
    "format_id = " + DEFAULT_FORMAT_ID + "\n"
    "comment = " + DEFAULT_COMMENT
};

inline const std::string COLORS[] {
    "black",
    "red",
    "green",
    "yellow",
    "blue",
    "magenta",
    "cyan",
    "white",

    "bright_black",
    "bright_red",
    "bright_green",
    "bright_yellow",
    "bright_blue",
    "bright_magenta",
    "bright_cyan",
    "bright_white"
};

inline const std::string HELP{

    "Usage\n\n"
    "\ttheme [options] <color-file-name> <output-dir>\n\n"
    "First argument that doesn't belong to any option goes to <color-file-name>, the second\n"
    "to <output-dir>. <output-dir> defaults to local config folder, checks performed in order: \n"
    "\t$XDG_CONFIG_HOME\n"
    "\t$HOME/.config\n\n"
    "Options:\n"
    "\t -o <output-dir> \t\t = Override output directory\n"
    "\t -f <file-name>  \t\t = Color config path\n\n"

};

inline const std::string DEFAULT_CONFIG_FORMAT{
    "#\tAutogenerated config\n"
    "\n"
    "#\tRegular colors:\n"

    //colors stored in numbers so no additional conversin is required
    "0\n"
    "1\n"
    "2\n"
    "3\n"
    "4\n"
    "5\n"
    "6\n"
    "7\n"

    "8\n"
    "9\n"
    "10\n"
    "11\n"
    "12\n"
    "13\n"
    "14\n"
    "15\n"
    "\n"
    "#Background and foreground -> test reload\n"
    "background\n"
    "foreground = #${red}\n"
    "\n"
    "#Custom colors\n"
};