#include <iostream>
#include <filesystem>
#include <fstream>
#include <algorithm>

#include "config.h"
#include "helpers.h"
#include <cstring>


/*Global settings*/
std::string output_dir{""};
std::string color_file{""};

//TODO: add examples
//TODO: ability to change config format
//TODO: proper color parsing so RGBA is supported
//TODO: file includes

const std::string config_format[] = {
    "#\tAutogenerated config\n",
    "\n",
    "#\tRegular colors:\n",

    //colors stored in numbers so no additional conversin is required
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",

    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "\n",
    "#Background and foreground\n",
    "background",
    "foreground",
    "\n",
    "#Custom colors\n"
};

namespace fs = std::filesystem;

void print_cfg(const ConfigSection& section_config, const ConfigSection& global_colors,  const ConfigSection& section_colors, std::ostream& stream);
std::string format_value(const std::string& format, const std::string& id_format, const std::string& key, const std::string& value);
int parse_arguments(const int argc, char* argv[]);

int main(int argc, char *argv[])
{

    //check if arguments parse successfully
    if(parse_arguments(argc, argv)) return -1;

    if(color_file.empty()) { std::cout << "No file provided!\nDo theme -h for help\n"; return -1; }
    
    //TODO verbose?
    //std::cout << "Parsing file " << fs::absolute(color_file) << "\n";
    //std::cout << "Output directory " << fs::absolute(output_dir) << "\n";


    fs::path config_dir{get_config_dir()};
    fs::path config_path{config_dir / "themer/config.conf"};

    create_conf(config_path);


    /*
        CONFIG FILE PARSING
    */

    //if(!fs::is_regular_file(config_path)) { std::cout << "File " << config_path << " doesn't exist!\n"; return -1;}

    std::vector<ConfigSection> config;
    parse_config( fs::path{config_path}, config );

    //check if section "default" exists
    //if not create it
    ConfigSection default_section;
    default_section.name = "default";

    if(auto loc = std::find_if(config.begin(), config.end(), [](const ConfigSection& sect){ return sect.name == "default"; }); loc != config.end()) default_section = *loc;

    //process all sections to remove raw data
    for(auto& sect : config)
    {
        if(sect.name != "default")
            process_config(default_section, sect, output_dir);
    }




    /*
        COLOR PARSING
    */
    std::vector<ConfigSection> COLORS;

    if(!fs::is_regular_file(color_file)) { std::cout << "File " << fs::absolute(color_file) << " doesn't exist!\n"; return -1; }

    parse_config( fs::path{color_file}, COLORS );

    ConfigSection default_colors;
    default_colors.name = "default";

    if(auto loc = std::find_if(COLORS.begin(), COLORS.end(), [](const ConfigSection& sect){ return sect.name == "default"; }); loc != COLORS.end()) default_colors = *loc;

    /*
        Prints colors to files
    */
    for(auto& sect : config)
    {
        /*for(const auto& [k, v] : sect.key_value_pairs)
        {
            std::cout << "\t" << k << ": " << v << "\n"; 
        }*/

        ConfigSection to_print;
        to_print.name = sect.name;

        if(auto loc = std::find_if(COLORS.begin(), COLORS.end(), [&sect](const ConfigSection& int_sect){ return int_sect.name == sect.name; }); loc != COLORS.end()) to_print = *loc;

        if(sect.name != "default")
        {
            fs::path path{sect.key_value_pairs["path"]};

            //config specifies filename not directory
            if(path.has_extension())
            {
                if(!fs::exists(path.parent_path())) fs::create_directories(path.parent_path());
            }else
            {
                if(!fs::exists(path)) fs::create_directories(path);
                if(fs::is_directory(path)) path /= "colors.conf";
            }

            std::cout << "Writing section "  << sect.name << " to " << fs::absolute(path) << "\n";

            std::ofstream file{path};
            print_cfg(sect, default_colors, to_print, file);
        }
    }
}

/*
    Parse arguments and setup variables
*/
int parse_arguments(const int argc, char* argv[])
{
    //if passing setting via -C, -f

    output_dir = get_config_dir();

    //if(argc == 1) { std::cout << "Invalid usage:\n" << HELP; return -1; };
    //if(argc == 2) { color_file = argv[1]; return 0;}
    //if(argc == 3) { color_file = argv[1]; output_dir = argv[2]; return 0;}

    for(int i = 1; i < argc; i++)
    {
        //boolean arguments
        if(strcmp(argv[i], "-h") == 0) { std::cout << HELP; continue;}

        //arguments that require another field
        if(i < argc-1)
        {
            if(strcmp(argv[i], "-o") == 0) { output_dir = argv[i+1]; i++; continue; }
            if(strcmp(argv[i], "-f") == 0) { color_file = argv[i+1]; i++; continue; }  
        }

        //none of the options match
        //the first non option argument is color_file, the second is output_dir
        if( color_file.empty() )    { color_file = argv[i]; continue; }
        else if( output_dir.empty() )  { output_dir = argv[i]; continue; }
    }

    return 0;
}
/*
    This actually prints the colors into a file
*/
void print_cfg(const ConfigSection& section_config, const ConfigSection& global_colors,  const ConfigSection& section_colors, std::ostream& stream)
{

    //all of these values should have benn configured in config.cpp: process_config
    std::string format = section_config.key_value_pairs.at("format");
    std::string id_format = section_config.key_value_pairs.at("format_id");
    std::string comment = section_config.key_value_pairs.at("comment");

    auto col_global = global_colors.key_value_pairs;
    auto col_section = section_colors.key_value_pairs;

    //std::cout << "Defaults: " << col_global << "\n";
    //std::cout << "Section: " << col_section << "\n";

    //unifies fields
    col_section.merge(col_global);

    //changes colors from names to indices wherever possible
    process_colors(col_section);

    /*
        Loop through config_format to set a more organized order of final file
    */
    for(const auto& line : config_format)
    {
        //insert a comment
        if(line.starts_with("#")) 
        {
            std::string out = line.substr(1);
            out = replace_all(out, "${section_name}", section_config.name); 
            out = replace_all(out, "${output_dir}", output_dir);
            out = replace_all(out, "${path}", section_config.key_value_pairs.at("path")); 

            stream << comment << line.substr(1) << "\n";
        }
        else if(line.starts_with("\n")) { stream << line; }
        else
        {
            if(col_section.contains(line))
            {
                stream << format_value(format, id_format, line, col_section[line]) << "\n";

                //erase the line so we can print the remainder under custom colors
                col_section.erase(line);
            }
            else
            {
                stream << comment << " Missing entry - " << line << "\n";
            }
        }
    }

    /*
        Loop through all the fields
        If color is one of the indexed ones (black, red, ...)
        Or provided as colorXXX where XXX is a number,
        Use alternate format
    */
    for(const auto [k, v] : col_section)
    {
       stream << format_value(format, id_format, k, v);
    }
}

std::string format_value(const std::string& format, const std::string& id_format, const std::string& key, const std::string& value)
{

    std::string formatted = format;

    //std::cout << key << ": " << value << "\n";
    //if key is a number
    try
    {
        int id = stoi(key);

        //if its a bae color (0-255) we use the other format;
        formatted = id_format;

        if(id >= 0 && id <= 15)
            formatted = replace_all(formatted, "${color_name}", COLORS[id]);

    }catch(std::exception e) {}

    formatted = replace_all(formatted, "${color_name}", key);
    formatted = replace_all(formatted, "${color_id}", key);
    formatted = replace_all(formatted, "${color_value}", value);

    return formatted;
}